### ISSUE TITLE
AddressSanitizer(test-units, CORS): SEGV @test_cors.cpp:175 in corsTest::updateResponseForAccessControl_test()

### ISSUE THREAD

**Issue by dwrobel** [pxscene/pxCore#1416]
I just rebased sources after my holiday and this is what I got:

```
=================================================================
==54==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6130000c5f42 at pc 0x7f95f3381745 bp 0x7ffde04e26f0 sp 0x7ffde04e1e98
WRITE of size 323 at 0x6130000c5f42 thread T0
    #0 0x7f95f3381744  (/lib64/libasan.so.5+0x49744)
    #1 0x6a40ba in corsTest::updateResponseForAccessControl_test() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_cors.cpp:175
    #2 0x697fb0 in corsTest_corsTests_Test::TestBody() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_cors.cpp:284
    #3 0x824e01 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtests+0x824e01)
    #4 0x8158bd in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2438
    #5 0x7ca500 in testing::Test::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2474
    #6 0x7cb991 in testing::TestInfo::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2656
    #7 0x7cc73f in testing::TestCase::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2774
    #8 0x7de867 in testing::internal::UnitTestImpl::RunAllTests() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:4649
    #9 0x828110 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2402
    #10 0x818080 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2438
    #11 0x7db767 in testing::UnitTest::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:4257
    #12 0x55189f in RUN_ALL_TESTS() (/home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtests+0x55189f)
    #13 0x5512c4 in main /home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtestsmain.cpp:119
    #14 0x7f95ee1ee18a in __libc_start_main (/lib64/libc.so.6+0x2318a)
    #15 0x550879 in _start (/home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtests+0x550879)

0x6130000c5f42 is located 0 bytes to the right of 322-byte region [0x6130000c5e00,0x6130000c5f42)
allocated by thread T0 here:
    #0 0x7f95f3428a50 in operator new[](unsigned long) (/lib64/libasan.so.5+0xf0a50)
    #1 0x6a408f in corsTest::updateResponseForAccessControl_test() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_cors.cpp:174
    #2 0x697fb0 in corsTest_corsTests_Test::TestBody() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_cors.cpp:284
    #3 0x824e01 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtests+0x824e01)
    #4 0x8158bd in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2438
    #5 0x7ca500 in testing::Test::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2474
    #6 0x7cb991 in testing::TestInfo::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2656
    #7 0x7cc73f in testing::TestCase::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2774
    #8 0x7de867 in testing::internal::UnitTestImpl::RunAllTests() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:4649
    #9 0x828110 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2402
    #10 0x818080 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:2438
    #11 0x7db767 in testing::UnitTest::Run() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/src/gtest.cc:4257
    #12 0x55189f in RUN_ALL_TESTS() (/home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtests+0x55189f)
    #13 0x5512c4 in main /home/sw/projects/pxscene/pxCore/tests/pxScene2d/pxscene2dtestsmain.cpp:119
    #14 0x7f95ee1ee18a in __libc_start_main (/lib64/libc.so.6+0x2318a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.5+0x49744) 
Shadow bytes around the buggy address:
  0x0c2680010b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2680010ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2680010bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2680010bc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2680010bd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2680010be0: 00 00 00 00 00 00 00 00[02]fa fa fa fa fa fa fa
  0x0c2680010bf0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c2680010c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2680010c10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2680010c20: 03 fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2680010c30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==54==ABORTING
```

**Comment by madanagopalt** [comment]
Thanks.
#https://github.com/pxscene/pxCore/pull/1417 added for addressing this.
